FROM node:22.9.0

WORKDIR /usr/src/app

COPY ./package*.json /usr/src/app/

# Optional: upgrade npm, not mandatory if already recent
RUN npm install -g npm@11.4.2

# ✅ Install project dependencies
RUN npm install

COPY ./ /usr/src/app/

EXPOSE 3000

CMD ["npm", "start"]